//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApiAUSA.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MOV_RELACION_NOTA_TAREA
    {
        public int rel_int_id { get; set; }
        public Nullable<int> tar_int_id { get; set; }
        public Nullable<int> not_int_id { get; set; }
    
        public virtual TBL_MOV_NOTA TBL_MOV_NOTA { get; set; }
        public virtual TBL_MOV_TAREA TBL_MOV_TAREA { get; set; }
    }
}
