//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApiAUSA.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MOV_NOTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MOV_NOTA()
        {
            this.TBL_MOV_RELACION_NOTA_TAREA = new HashSet<TBL_MOV_RELACION_NOTA_TAREA>();
        }
    
        public int not_int_id { get; set; }
        public string not_str_archivo { get; set; }
        public int not_bit_anulado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MOV_RELACION_NOTA_TAREA> TBL_MOV_RELACION_NOTA_TAREA { get; set; }
    }
}
