//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApiAUSA.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MOV_TAREAS_TIPO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MOV_TAREAS_TIPO()
        {
            this.TBL_MOV_TAREA = new HashSet<TBL_MOV_TAREA>();
        }
    
        public int tiptar_int_id { get; set; }
        public string tiptar_str_nombre { get; set; }
        public string tiptar_str_descripcion { get; set; }
        public Nullable<int> tiptar_int_estado { get; set; }
        public int tiptar_int_usrcreacion { get; set; }
        public System.DateTime tiptar_dat_fcreacion { get; set; }
        public Nullable<int> tiptar_int_usrmodif { get; set; }
        public Nullable<System.DateTime> tiptar_dat_ultimamodif { get; set; }
        public int tptar_bit_anulado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MOV_TAREA> TBL_MOV_TAREA { get; set; }
    }
}
