//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApiAUSA.Entities.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBAUSA_PYMOVILEntities : DbContext
    {
        public DBAUSA_PYMOVILEntities()
            : base("name=DBAUSA_PYMOVILEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_MOV_NOTA> TBL_MOV_NOTA { get; set; }
        public virtual DbSet<TBL_MOV_RELACION_CLIENTE_TAREA> TBL_MOV_RELACION_CLIENTE_TAREA { get; set; }
        public virtual DbSet<TBL_MOV_RELACION_NOTA_TAREA> TBL_MOV_RELACION_NOTA_TAREA { get; set; }
        public virtual DbSet<TBL_MOV_TAREA> TBL_MOV_TAREA { get; set; }
        public virtual DbSet<TBL_MOV_TAREAS_TIPO> TBL_MOV_TAREAS_TIPO { get; set; }
    
        public virtual ObjectResult<PA_MOV_CLIENTE_CONDICIONPAGO_Result> PA_MOV_CLIENTE_CONDICIONPAGO(Nullable<int> cliente)
        {
            var clienteParameter = cliente.HasValue ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_CLIENTE_CONDICIONPAGO_Result>("PA_MOV_CLIENTE_CONDICIONPAGO", clienteParameter);
        }
    
        public virtual ObjectResult<PA_MOV_CLIENTE_CONDICIONPAGO_DETALLE_Result> PA_MOV_CLIENTE_CONDICIONPAGO_DETALLE(Nullable<int> cliente)
        {
            var clienteParameter = cliente.HasValue ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_CLIENTE_CONDICIONPAGO_DETALLE_Result>("PA_MOV_CLIENTE_CONDICIONPAGO_DETALLE", clienteParameter);
        }
    
        public virtual ObjectResult<PA_MOV_CLIENTE_CONTACTOS_Result> PA_MOV_CLIENTE_CONTACTOS(Nullable<int> cliente, Nullable<int> contacto)
        {
            var clienteParameter = cliente.HasValue ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(int));
    
            var contactoParameter = contacto.HasValue ?
                new ObjectParameter("contacto", contacto) :
                new ObjectParameter("contacto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_CLIENTE_CONTACTOS_Result>("PA_MOV_CLIENTE_CONTACTOS", clienteParameter, contactoParameter);
        }
    
        public virtual ObjectResult<PA_MOV_CLIENTE_CONTACTOS_TELEFONOS_Result> PA_MOV_CLIENTE_CONTACTOS_TELEFONOS(Nullable<int> cliente, Nullable<int> contacto)
        {
            var clienteParameter = cliente.HasValue ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(int));
    
            var contactoParameter = contacto.HasValue ?
                new ObjectParameter("contacto", contacto) :
                new ObjectParameter("contacto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_CLIENTE_CONTACTOS_TELEFONOS_Result>("PA_MOV_CLIENTE_CONTACTOS_TELEFONOS", clienteParameter, contactoParameter);
        }
    
        public virtual ObjectResult<PA_MOV_CLIENTE_DESPACHO_Result> PA_MOV_CLIENTE_DESPACHO(Nullable<int> orden, string referencia)
        {
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("orden", orden) :
                new ObjectParameter("orden", typeof(int));
    
            var referenciaParameter = referencia != null ?
                new ObjectParameter("referencia", referencia) :
                new ObjectParameter("referencia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_CLIENTE_DESPACHO_Result>("PA_MOV_CLIENTE_DESPACHO", ordenParameter, referenciaParameter);
        }
    
        public virtual ObjectResult<PA_MOV_CLIENTE_MOROSIDAD_UTILIZACION_LINEA_Result> PA_MOV_CLIENTE_MOROSIDAD_UTILIZACION_LINEA(Nullable<int> cliente)
        {
            var clienteParameter = cliente.HasValue ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_CLIENTE_MOROSIDAD_UTILIZACION_LINEA_Result>("PA_MOV_CLIENTE_MOROSIDAD_UTILIZACION_LINEA", clienteParameter);
        }
    
        public virtual ObjectResult<PA_MOV_CLIENTE_PARTICIPACION_Result> PA_MOV_CLIENTE_PARTICIPACION(Nullable<int> cliente)
        {
            var clienteParameter = cliente.HasValue ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_CLIENTE_PARTICIPACION_Result>("PA_MOV_CLIENTE_PARTICIPACION", clienteParameter);
        }
    
        public virtual ObjectResult<PA_MOV_CLIENTE_PARTICIPACION_DETALLE_Result> PA_MOV_CLIENTE_PARTICIPACION_DETALLE(Nullable<int> cliente)
        {
            var clienteParameter = cliente.HasValue ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_CLIENTE_PARTICIPACION_DETALLE_Result>("PA_MOV_CLIENTE_PARTICIPACION_DETALLE", clienteParameter);
        }
    
        public virtual ObjectResult<PA_MOV_CLIENTE_TARIFAS_Result> PA_MOV_CLIENTE_TARIFAS(Nullable<int> cliente)
        {
            var clienteParameter = cliente.HasValue ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_CLIENTE_TARIFAS_Result>("PA_MOV_CLIENTE_TARIFAS", clienteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_MOV_DEVOLVER_IDUSUARIO(string usr)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_MOV_DEVOLVER_IDUSUARIO", usrParameter);
        }
    
        public virtual int PA_MOV_NOTA_DELETE(Nullable<int> not_int_id)
        {
            var not_int_idParameter = not_int_id.HasValue ?
                new ObjectParameter("not_int_id", not_int_id) :
                new ObjectParameter("not_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_NOTA_DELETE", not_int_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> PA_MOV_NOTA_INSERT(string not_str_archivo)
        {
            var not_str_archivoParameter = not_str_archivo != null ?
                new ObjectParameter("not_str_archivo", not_str_archivo) :
                new ObjectParameter("not_str_archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("PA_MOV_NOTA_INSERT", not_str_archivoParameter);
        }
    
        public virtual ObjectResult<PA_MOV_NOTA_SELECT_Result> PA_MOV_NOTA_SELECT(Nullable<int> not_int_id)
        {
            var not_int_idParameter = not_int_id.HasValue ?
                new ObjectParameter("not_int_id", not_int_id) :
                new ObjectParameter("not_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_NOTA_SELECT_Result>("PA_MOV_NOTA_SELECT", not_int_idParameter);
        }
    
        public virtual int PA_MOV_NOTA_UPDATE(Nullable<int> not_int_id, string not_str_archivo)
        {
            var not_int_idParameter = not_int_id.HasValue ?
                new ObjectParameter("not_int_id", not_int_id) :
                new ObjectParameter("not_int_id", typeof(int));
    
            var not_str_archivoParameter = not_str_archivo != null ?
                new ObjectParameter("not_str_archivo", not_str_archivo) :
                new ObjectParameter("not_str_archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_NOTA_UPDATE", not_int_idParameter, not_str_archivoParameter);
        }
    
        public virtual int PA_MOV_NOTA_UPDATE_2(string not_str_archivo, string new_str_archivo)
        {
            var not_str_archivoParameter = not_str_archivo != null ?
                new ObjectParameter("not_str_archivo", not_str_archivo) :
                new ObjectParameter("not_str_archivo", typeof(string));
    
            var new_str_archivoParameter = new_str_archivo != null ?
                new ObjectParameter("new_str_archivo", new_str_archivo) :
                new ObjectParameter("new_str_archivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_NOTA_UPDATE_2", not_str_archivoParameter, new_str_archivoParameter);
        }
    
        public virtual ObjectResult<PA_MOV_OPERACIONES_DESPACHADORES_Result> PA_MOV_OPERACIONES_DESPACHADORES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_OPERACIONES_DESPACHADORES_Result>("PA_MOV_OPERACIONES_DESPACHADORES");
        }
    
        public virtual ObjectResult<PA_MOV_OPERACIONES_DETALLE_Result> PA_MOV_OPERACIONES_DETALLE(Nullable<int> ope_int_id)
        {
            var ope_int_idParameter = ope_int_id.HasValue ?
                new ObjectParameter("ope_int_id", ope_int_id) :
                new ObjectParameter("ope_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_OPERACIONES_DETALLE_Result>("PA_MOV_OPERACIONES_DETALLE", ope_int_idParameter);
        }
    
        public virtual int PA_MOV_OPERACIONES_INICIAR(Nullable<int> ope_int_id, Nullable<int> usr_int_id)
        {
            var ope_int_idParameter = ope_int_id.HasValue ?
                new ObjectParameter("ope_int_id", ope_int_id) :
                new ObjectParameter("ope_int_id", typeof(int));
    
            var usr_int_idParameter = usr_int_id.HasValue ?
                new ObjectParameter("usr_int_id", usr_int_id) :
                new ObjectParameter("usr_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_OPERACIONES_INICIAR", ope_int_idParameter, usr_int_idParameter);
        }
    
        public virtual ObjectResult<PA_MOV_OPERACIONES_LISTAR_Result> PA_MOV_OPERACIONES_LISTAR(Nullable<int> ope_int_despachador, Nullable<int> cli_int_id, Nullable<int> ord_int_id, Nullable<System.DateTime> fecha, Nullable<int> alm_int_id, Nullable<int> estado)
        {
            var ope_int_despachadorParameter = ope_int_despachador.HasValue ?
                new ObjectParameter("ope_int_despachador", ope_int_despachador) :
                new ObjectParameter("ope_int_despachador", typeof(int));
    
            var cli_int_idParameter = cli_int_id.HasValue ?
                new ObjectParameter("cli_int_id", cli_int_id) :
                new ObjectParameter("cli_int_id", typeof(int));
    
            var ord_int_idParameter = ord_int_id.HasValue ?
                new ObjectParameter("ord_int_id", ord_int_id) :
                new ObjectParameter("ord_int_id", typeof(int));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var alm_int_idParameter = alm_int_id.HasValue ?
                new ObjectParameter("alm_int_id", alm_int_id) :
                new ObjectParameter("alm_int_id", typeof(int));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_OPERACIONES_LISTAR_Result>("PA_MOV_OPERACIONES_LISTAR", ope_int_despachadorParameter, cli_int_idParameter, ord_int_idParameter, fechaParameter, alm_int_idParameter, estadoParameter);
        }
    
        public virtual ObjectResult<PA_MOV_OPERACIONES_OPCIONES_Result> PA_MOV_OPERACIONES_OPCIONES(Nullable<int> ope_int_id)
        {
            var ope_int_idParameter = ope_int_id.HasValue ?
                new ObjectParameter("ope_int_id", ope_int_id) :
                new ObjectParameter("ope_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_OPERACIONES_OPCIONES_Result>("PA_MOV_OPERACIONES_OPCIONES", ope_int_idParameter);
        }
    
        public virtual int PA_MOV_OPERACIONES_PERMISOOK(Nullable<int> ope_int_id, Nullable<int> usr_int_id)
        {
            var ope_int_idParameter = ope_int_id.HasValue ?
                new ObjectParameter("ope_int_id", ope_int_id) :
                new ObjectParameter("ope_int_id", typeof(int));
    
            var usr_int_idParameter = usr_int_id.HasValue ?
                new ObjectParameter("usr_int_id", usr_int_id) :
                new ObjectParameter("usr_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_OPERACIONES_PERMISOOK", ope_int_idParameter, usr_int_idParameter);
        }
    
        public virtual int PA_MOV_OPERACIONES_REASGINACION(Nullable<int> ope_int_id, Nullable<int> ope_int_despachador, string ope_str_observacion)
        {
            var ope_int_idParameter = ope_int_id.HasValue ?
                new ObjectParameter("ope_int_id", ope_int_id) :
                new ObjectParameter("ope_int_id", typeof(int));
    
            var ope_int_despachadorParameter = ope_int_despachador.HasValue ?
                new ObjectParameter("ope_int_despachador", ope_int_despachador) :
                new ObjectParameter("ope_int_despachador", typeof(int));
    
            var ope_str_observacionParameter = ope_str_observacion != null ?
                new ObjectParameter("ope_str_observacion", ope_str_observacion) :
                new ObjectParameter("ope_str_observacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_OPERACIONES_REASGINACION", ope_int_idParameter, ope_int_despachadorParameter, ope_str_observacionParameter);
        }
    
        public virtual int PA_MOV_OPERACIONES_SOLICITARTRANSPORTE(Nullable<int> ope_int_id, Nullable<int> usr_int_id)
        {
            var ope_int_idParameter = ope_int_id.HasValue ?
                new ObjectParameter("ope_int_id", ope_int_id) :
                new ObjectParameter("ope_int_id", typeof(int));
    
            var usr_int_idParameter = usr_int_id.HasValue ?
                new ObjectParameter("usr_int_id", usr_int_id) :
                new ObjectParameter("usr_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_OPERACIONES_SOLICITARTRANSPORTE", ope_int_idParameter, usr_int_idParameter);
        }
    
        public virtual int PA_MOV_OPERACIONES_TERMINAR(Nullable<int> ope_int_id, Nullable<int> usr_int_id)
        {
            var ope_int_idParameter = ope_int_id.HasValue ?
                new ObjectParameter("ope_int_id", ope_int_id) :
                new ObjectParameter("ope_int_id", typeof(int));
    
            var usr_int_idParameter = usr_int_id.HasValue ?
                new ObjectParameter("usr_int_id", usr_int_id) :
                new ObjectParameter("usr_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_OPERACIONES_TERMINAR", ope_int_idParameter, usr_int_idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_MOV_ORDEN_ID(Nullable<int> anio, string numero, Nullable<int> cliente)
        {
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            var numeroParameter = numero != null ?
                new ObjectParameter("numero", numero) :
                new ObjectParameter("numero", typeof(string));
    
            var clienteParameter = cliente.HasValue ?
                new ObjectParameter("cliente", cliente) :
                new ObjectParameter("cliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_MOV_ORDEN_ID", anioParameter, numeroParameter, clienteParameter);
        }
    
        public virtual int PA_MOV_RELACION_CLIENTE_TAREA_DELETE(Nullable<int> tar_int_id, Nullable<int> cli_int_id)
        {
            var tar_int_idParameter = tar_int_id.HasValue ?
                new ObjectParameter("tar_int_id", tar_int_id) :
                new ObjectParameter("tar_int_id", typeof(int));
    
            var cli_int_idParameter = cli_int_id.HasValue ?
                new ObjectParameter("cli_int_id", cli_int_id) :
                new ObjectParameter("cli_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_RELACION_CLIENTE_TAREA_DELETE", tar_int_idParameter, cli_int_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> PA_MOV_RELACION_CLIENTE_TAREA_INSERT(Nullable<int> tar_int_id, Nullable<int> cli_int_id)
        {
            var tar_int_idParameter = tar_int_id.HasValue ?
                new ObjectParameter("tar_int_id", tar_int_id) :
                new ObjectParameter("tar_int_id", typeof(int));
    
            var cli_int_idParameter = cli_int_id.HasValue ?
                new ObjectParameter("cli_int_id", cli_int_id) :
                new ObjectParameter("cli_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("PA_MOV_RELACION_CLIENTE_TAREA_INSERT", tar_int_idParameter, cli_int_idParameter);
        }
    
        public virtual ObjectResult<PA_MOV_RELACION_CLIENTE_TAREA_SELECT_Result> PA_MOV_RELACION_CLIENTE_TAREA_SELECT(Nullable<int> tar_int_id)
        {
            var tar_int_idParameter = tar_int_id.HasValue ?
                new ObjectParameter("tar_int_id", tar_int_id) :
                new ObjectParameter("tar_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_RELACION_CLIENTE_TAREA_SELECT_Result>("PA_MOV_RELACION_CLIENTE_TAREA_SELECT", tar_int_idParameter);
        }
    
        public virtual int PA_MOV_RELACION_CLIENTE_TAREA_UPDATE(Nullable<int> rel_int_id, Nullable<int> tar_int_id, Nullable<int> cli_int_id)
        {
            var rel_int_idParameter = rel_int_id.HasValue ?
                new ObjectParameter("rel_int_id", rel_int_id) :
                new ObjectParameter("rel_int_id", typeof(int));
    
            var tar_int_idParameter = tar_int_id.HasValue ?
                new ObjectParameter("tar_int_id", tar_int_id) :
                new ObjectParameter("tar_int_id", typeof(int));
    
            var cli_int_idParameter = cli_int_id.HasValue ?
                new ObjectParameter("cli_int_id", cli_int_id) :
                new ObjectParameter("cli_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_RELACION_CLIENTE_TAREA_UPDATE", rel_int_idParameter, tar_int_idParameter, cli_int_idParameter);
        }
    
        public virtual int PA_MOV_RELACION_NOTA_TAREA_DELETE(Nullable<int> tar_int_id, Nullable<int> not_int_id)
        {
            var tar_int_idParameter = tar_int_id.HasValue ?
                new ObjectParameter("tar_int_id", tar_int_id) :
                new ObjectParameter("tar_int_id", typeof(int));
    
            var not_int_idParameter = not_int_id.HasValue ?
                new ObjectParameter("not_int_id", not_int_id) :
                new ObjectParameter("not_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_RELACION_NOTA_TAREA_DELETE", tar_int_idParameter, not_int_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> PA_MOV_RELACION_NOTA_TAREA_INSERT(Nullable<int> tar_int_id, Nullable<int> not_int_id)
        {
            var tar_int_idParameter = tar_int_id.HasValue ?
                new ObjectParameter("tar_int_id", tar_int_id) :
                new ObjectParameter("tar_int_id", typeof(int));
    
            var not_int_idParameter = not_int_id.HasValue ?
                new ObjectParameter("not_int_id", not_int_id) :
                new ObjectParameter("not_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("PA_MOV_RELACION_NOTA_TAREA_INSERT", tar_int_idParameter, not_int_idParameter);
        }
    
        public virtual ObjectResult<PA_MOV_RELACION_NOTA_TAREA_SELECT_Result> PA_MOV_RELACION_NOTA_TAREA_SELECT(Nullable<int> tar_int_id)
        {
            var tar_int_idParameter = tar_int_id.HasValue ?
                new ObjectParameter("tar_int_id", tar_int_id) :
                new ObjectParameter("tar_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_RELACION_NOTA_TAREA_SELECT_Result>("PA_MOV_RELACION_NOTA_TAREA_SELECT", tar_int_idParameter);
        }
    
        public virtual int PA_MOV_RELACION_NOTA_TAREA_UPDATE(Nullable<int> rel_int_id, Nullable<int> tar_int_id, Nullable<int> not_int_id)
        {
            var rel_int_idParameter = rel_int_id.HasValue ?
                new ObjectParameter("rel_int_id", rel_int_id) :
                new ObjectParameter("rel_int_id", typeof(int));
    
            var tar_int_idParameter = tar_int_id.HasValue ?
                new ObjectParameter("tar_int_id", tar_int_id) :
                new ObjectParameter("tar_int_id", typeof(int));
    
            var not_int_idParameter = not_int_id.HasValue ?
                new ObjectParameter("not_int_id", not_int_id) :
                new ObjectParameter("not_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_RELACION_NOTA_TAREA_UPDATE", rel_int_idParameter, tar_int_idParameter, not_int_idParameter);
        }
    
        public virtual int PA_MOV_TAREA_DELETE(Nullable<int> tar_int_id)
        {
            var tar_int_idParameter = tar_int_id.HasValue ?
                new ObjectParameter("tar_int_id", tar_int_id) :
                new ObjectParameter("tar_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_TAREA_DELETE", tar_int_idParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> PA_MOV_TAREA_INSERT(Nullable<int> tiptar_int_id, Nullable<int> usr_int_id, Nullable<int> tar_int_prioridad, Nullable<System.DateTime> tar_dat_fchlimite, string tar_txt_detalle, Nullable<int> tar_int_estado, string tar_str_observacion, string tar_str_orden)
        {
            var tiptar_int_idParameter = tiptar_int_id.HasValue ?
                new ObjectParameter("tiptar_int_id", tiptar_int_id) :
                new ObjectParameter("tiptar_int_id", typeof(int));
    
            var usr_int_idParameter = usr_int_id.HasValue ?
                new ObjectParameter("usr_int_id", usr_int_id) :
                new ObjectParameter("usr_int_id", typeof(int));
    
            var tar_int_prioridadParameter = tar_int_prioridad.HasValue ?
                new ObjectParameter("tar_int_prioridad", tar_int_prioridad) :
                new ObjectParameter("tar_int_prioridad", typeof(int));
    
            var tar_dat_fchlimiteParameter = tar_dat_fchlimite.HasValue ?
                new ObjectParameter("tar_dat_fchlimite", tar_dat_fchlimite) :
                new ObjectParameter("tar_dat_fchlimite", typeof(System.DateTime));
    
            var tar_txt_detalleParameter = tar_txt_detalle != null ?
                new ObjectParameter("tar_txt_detalle", tar_txt_detalle) :
                new ObjectParameter("tar_txt_detalle", typeof(string));
    
            var tar_int_estadoParameter = tar_int_estado.HasValue ?
                new ObjectParameter("tar_int_estado", tar_int_estado) :
                new ObjectParameter("tar_int_estado", typeof(int));
    
            var tar_str_observacionParameter = tar_str_observacion != null ?
                new ObjectParameter("tar_str_observacion", tar_str_observacion) :
                new ObjectParameter("tar_str_observacion", typeof(string));
    
            var tar_str_ordenParameter = tar_str_orden != null ?
                new ObjectParameter("tar_str_orden", tar_str_orden) :
                new ObjectParameter("tar_str_orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("PA_MOV_TAREA_INSERT", tiptar_int_idParameter, usr_int_idParameter, tar_int_prioridadParameter, tar_dat_fchlimiteParameter, tar_txt_detalleParameter, tar_int_estadoParameter, tar_str_observacionParameter, tar_str_ordenParameter);
        }
    
        public virtual ObjectResult<PA_MOV_TAREA_SELECT_Result> PA_MOV_TAREA_SELECT(Nullable<int> usr_int_id)
        {
            var usr_int_idParameter = usr_int_id.HasValue ?
                new ObjectParameter("usr_int_id", usr_int_id) :
                new ObjectParameter("usr_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_TAREA_SELECT_Result>("PA_MOV_TAREA_SELECT", usr_int_idParameter);
        }
    
        public virtual ObjectResult<PA_MOV_TAREA_TIPO_SELECT_Result> PA_MOV_TAREA_TIPO_SELECT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_TAREA_TIPO_SELECT_Result>("PA_MOV_TAREA_TIPO_SELECT");
        }
    
        public virtual int PA_MOV_TAREA_UPDATE(Nullable<int> tar_int_id, Nullable<int> tiptar_int_id, Nullable<int> usr_int_id, Nullable<int> tar_int_prioridad, Nullable<System.DateTime> tar_dat_fchlimite, string tar_txt_detalle, Nullable<int> tar_int_estado, string tar_str_observacion, string tar_str_orden)
        {
            var tar_int_idParameter = tar_int_id.HasValue ?
                new ObjectParameter("tar_int_id", tar_int_id) :
                new ObjectParameter("tar_int_id", typeof(int));
    
            var tiptar_int_idParameter = tiptar_int_id.HasValue ?
                new ObjectParameter("tiptar_int_id", tiptar_int_id) :
                new ObjectParameter("tiptar_int_id", typeof(int));
    
            var usr_int_idParameter = usr_int_id.HasValue ?
                new ObjectParameter("usr_int_id", usr_int_id) :
                new ObjectParameter("usr_int_id", typeof(int));
    
            var tar_int_prioridadParameter = tar_int_prioridad.HasValue ?
                new ObjectParameter("tar_int_prioridad", tar_int_prioridad) :
                new ObjectParameter("tar_int_prioridad", typeof(int));
    
            var tar_dat_fchlimiteParameter = tar_dat_fchlimite.HasValue ?
                new ObjectParameter("tar_dat_fchlimite", tar_dat_fchlimite) :
                new ObjectParameter("tar_dat_fchlimite", typeof(System.DateTime));
    
            var tar_txt_detalleParameter = tar_txt_detalle != null ?
                new ObjectParameter("tar_txt_detalle", tar_txt_detalle) :
                new ObjectParameter("tar_txt_detalle", typeof(string));
    
            var tar_int_estadoParameter = tar_int_estado.HasValue ?
                new ObjectParameter("tar_int_estado", tar_int_estado) :
                new ObjectParameter("tar_int_estado", typeof(int));
    
            var tar_str_observacionParameter = tar_str_observacion != null ?
                new ObjectParameter("tar_str_observacion", tar_str_observacion) :
                new ObjectParameter("tar_str_observacion", typeof(string));
    
            var tar_str_ordenParameter = tar_str_orden != null ?
                new ObjectParameter("tar_str_orden", tar_str_orden) :
                new ObjectParameter("tar_str_orden", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_TAREA_UPDATE", tar_int_idParameter, tiptar_int_idParameter, usr_int_idParameter, tar_int_prioridadParameter, tar_dat_fchlimiteParameter, tar_txt_detalleParameter, tar_int_estadoParameter, tar_str_observacionParameter, tar_str_ordenParameter);
        }
    
        public virtual int PA_MOV_TAREAS_TIPO_DELETE(Nullable<int> tiptar_int_id, Nullable<int> tiptar_int_usrcreacion)
        {
            var tiptar_int_idParameter = tiptar_int_id.HasValue ?
                new ObjectParameter("tiptar_int_id", tiptar_int_id) :
                new ObjectParameter("tiptar_int_id", typeof(int));
    
            var tiptar_int_usrcreacionParameter = tiptar_int_usrcreacion.HasValue ?
                new ObjectParameter("tiptar_int_usrcreacion", tiptar_int_usrcreacion) :
                new ObjectParameter("tiptar_int_usrcreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_TAREAS_TIPO_DELETE", tiptar_int_idParameter, tiptar_int_usrcreacionParameter);
        }
    
        public virtual int PA_MOV_TAREAS_TIPO_INSERT(string tiptar_str_nombre, string tiptar_str_descripcion, Nullable<int> tiptar_int_estado, Nullable<int> tiptar_int_usrmodif, Nullable<int> tiptar_int_usrcreacion)
        {
            var tiptar_str_nombreParameter = tiptar_str_nombre != null ?
                new ObjectParameter("tiptar_str_nombre", tiptar_str_nombre) :
                new ObjectParameter("tiptar_str_nombre", typeof(string));
    
            var tiptar_str_descripcionParameter = tiptar_str_descripcion != null ?
                new ObjectParameter("tiptar_str_descripcion", tiptar_str_descripcion) :
                new ObjectParameter("tiptar_str_descripcion", typeof(string));
    
            var tiptar_int_estadoParameter = tiptar_int_estado.HasValue ?
                new ObjectParameter("tiptar_int_estado", tiptar_int_estado) :
                new ObjectParameter("tiptar_int_estado", typeof(int));
    
            var tiptar_int_usrmodifParameter = tiptar_int_usrmodif.HasValue ?
                new ObjectParameter("tiptar_int_usrmodif", tiptar_int_usrmodif) :
                new ObjectParameter("tiptar_int_usrmodif", typeof(int));
    
            var tiptar_int_usrcreacionParameter = tiptar_int_usrcreacion.HasValue ?
                new ObjectParameter("tiptar_int_usrcreacion", tiptar_int_usrcreacion) :
                new ObjectParameter("tiptar_int_usrcreacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_TAREAS_TIPO_INSERT", tiptar_str_nombreParameter, tiptar_str_descripcionParameter, tiptar_int_estadoParameter, tiptar_int_usrmodifParameter, tiptar_int_usrcreacionParameter);
        }
    
        public virtual int PA_MOV_TAREAS_TIPO_UPDATE(Nullable<int> tiptar_int_id, string tiptar_str_nombre, string tiptar_str_descripcion, Nullable<int> tiptar_int_estado, Nullable<int> tiptar_int_usrmodif)
        {
            var tiptar_int_idParameter = tiptar_int_id.HasValue ?
                new ObjectParameter("tiptar_int_id", tiptar_int_id) :
                new ObjectParameter("tiptar_int_id", typeof(int));
    
            var tiptar_str_nombreParameter = tiptar_str_nombre != null ?
                new ObjectParameter("tiptar_str_nombre", tiptar_str_nombre) :
                new ObjectParameter("tiptar_str_nombre", typeof(string));
    
            var tiptar_str_descripcionParameter = tiptar_str_descripcion != null ?
                new ObjectParameter("tiptar_str_descripcion", tiptar_str_descripcion) :
                new ObjectParameter("tiptar_str_descripcion", typeof(string));
    
            var tiptar_int_estadoParameter = tiptar_int_estado.HasValue ?
                new ObjectParameter("tiptar_int_estado", tiptar_int_estado) :
                new ObjectParameter("tiptar_int_estado", typeof(int));
    
            var tiptar_int_usrmodifParameter = tiptar_int_usrmodif.HasValue ?
                new ObjectParameter("tiptar_int_usrmodif", tiptar_int_usrmodif) :
                new ObjectParameter("tiptar_int_usrmodif", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PA_MOV_TAREAS_TIPO_UPDATE", tiptar_int_idParameter, tiptar_str_nombreParameter, tiptar_str_descripcionParameter, tiptar_int_estadoParameter, tiptar_int_usrmodifParameter);
        }
    
        public virtual ObjectResult<PA_MOV_USUARIO_CARTERA_CLIENTES_Result> PA_MOV_USUARIO_CARTERA_CLIENTES(Nullable<int> usr)
        {
            var usrParameter = usr.HasValue ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_USUARIO_CARTERA_CLIENTES_Result>("PA_MOV_USUARIO_CARTERA_CLIENTES", usrParameter);
        }
    
        public virtual ObjectResult<string> PA_MOV_USUARIO_DATOS(Nullable<int> usr_int_id)
        {
            var usr_int_idParameter = usr_int_id.HasValue ?
                new ObjectParameter("usr_int_id", usr_int_id) :
                new ObjectParameter("usr_int_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PA_MOV_USUARIO_DATOS", usr_int_idParameter);
        }
    
        public virtual ObjectResult<PA_MOV_USUARIO_ROL_Result> PA_MOV_USUARIO_ROL(Nullable<int> usr)
        {
            var usrParameter = usr.HasValue ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_MOV_USUARIO_ROL_Result>("PA_MOV_USUARIO_ROL", usrParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> PA_MOV_VALIDAR_USUARIO_EXTERNO(string usr, string clave)
        {
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("PA_MOV_VALIDAR_USUARIO_EXTERNO", usrParameter, claveParameter);
        }
    }
}
