//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWebApiAUSA.Entities.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MOV_TAREA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MOV_TAREA()
        {
            this.TBL_MOV_RELACION_CLIENTE_TAREA = new HashSet<TBL_MOV_RELACION_CLIENTE_TAREA>();
            this.TBL_MOV_RELACION_NOTA_TAREA = new HashSet<TBL_MOV_RELACION_NOTA_TAREA>();
        }
    
        public int tar_int_id { get; set; }
        public int tiptar_int_id { get; set; }
        public int usr_int_id { get; set; }
        public Nullable<int> tar_int_prioridad { get; set; }
        public Nullable<System.DateTime> tar_dat_fchcreacion { get; set; }
        public Nullable<System.DateTime> tar_dat_fchmodificacion { get; set; }
        public Nullable<System.DateTime> tar_dat_fchlimite { get; set; }
        public string tar_txt_detalle { get; set; }
        public Nullable<int> tar_int_estado { get; set; }
        public string tar_str_observacion { get; set; }
        public string tar_str_orden { get; set; }
        public Nullable<int> tar_bit_anulado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MOV_RELACION_CLIENTE_TAREA> TBL_MOV_RELACION_CLIENTE_TAREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_MOV_RELACION_NOTA_TAREA> TBL_MOV_RELACION_NOTA_TAREA { get; set; }
        public virtual TBL_MOV_TAREAS_TIPO TBL_MOV_TAREAS_TIPO { get; set; }
    }
}
